// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Audit struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedDate          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	ModifiedDate         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=modifiedDate,proto3" json:"modifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Audit) Reset()         { *m = Audit{} }
func (m *Audit) String() string { return proto.CompactTextString(m) }
func (*Audit) ProtoMessage()    {}
func (*Audit) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_29f7b0acf086b94b, []int{0}
}
func (m *Audit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audit.Unmarshal(m, b)
}
func (m *Audit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audit.Marshal(b, m, deterministic)
}
func (dst *Audit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audit.Merge(dst, src)
}
func (m *Audit) XXX_Size() int {
	return xxx_messageInfo_Audit.Size(m)
}
func (m *Audit) XXX_DiscardUnknown() {
	xxx_messageInfo_Audit.DiscardUnknown(m)
}

var xxx_messageInfo_Audit proto.InternalMessageInfo

func (m *Audit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Audit) GetCreatedDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedDate
	}
	return nil
}

func (m *Audit) GetModifiedDate() *timestamp.Timestamp {
	if m != nil {
		return m.ModifiedDate
	}
	return nil
}

func init() {
	proto.RegisterType((*Audit)(nil), "proto.Audit")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_29f7b0acf086b94b) }

var fileDescriptor_common_29f7b0acf086b94b = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xf2, 0xe9, 0xf9,
	0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x5e, 0x52, 0x69, 0x9a, 0x7e, 0x49, 0x66, 0x6e, 0x6a, 0x71,
	0x49, 0x62, 0x6e, 0x01, 0x44, 0x9d, 0xd2, 0x54, 0x46, 0x2e, 0x56, 0xc7, 0xd2, 0x94, 0xcc, 0x12,
	0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14,
	0x21, 0x1b, 0x2e, 0xee, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x14, 0x97, 0xc4, 0x92, 0x54, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x29, 0x3d, 0x88, 0x81, 0x7a, 0x30, 0x03, 0xf5, 0x42, 0x60,
	0x06, 0x06, 0x21, 0x2b, 0x17, 0xb2, 0xe3, 0xe2, 0xc9, 0xcd, 0x4f, 0xc9, 0x4c, 0xcb, 0x84, 0x6a,
	0x67, 0x26, 0xa8, 0x1d, 0x45, 0x7d, 0x12, 0x1b, 0x58, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xba, 0x8d, 0xf9, 0xbc, 0xd6, 0x00, 0x00, 0x00,
}
