// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContactType int32

const (
	ContactType_UnknownContactType    ContactType = 0
	ContactType_AdminContactType      ContactType = 1
	ContactType_SubscriberContactType ContactType = 2
	ContactType_FriendContactType     ContactType = 3
)

var ContactType_name = map[int32]string{
	0: "UnknownContactType",
	1: "AdminContactType",
	2: "SubscriberContactType",
	3: "FriendContactType",
}
var ContactType_value = map[string]int32{
	"UnknownContactType":    0,
	"AdminContactType":      1,
	"SubscriberContactType": 2,
	"FriendContactType":     3,
}

func (x ContactType) String() string {
	return proto.EnumName(ContactType_name, int32(x))
}
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{0}
}

type CallType int32

const (
	CallType_UnknownCallType   CallType = 0
	CallType_TelVoiceCallType  CallType = 1
	CallType_DataVoiceCallType CallType = 2
	CallType_DataVideoCallType CallType = 3
)

var CallType_name = map[int32]string{
	0: "UnknownCallType",
	1: "TelVoiceCallType",
	2: "DataVoiceCallType",
	3: "DataVideoCallType",
}
var CallType_value = map[string]int32{
	"UnknownCallType":   0,
	"TelVoiceCallType":  1,
	"DataVoiceCallType": 2,
	"DataVideoCallType": 3,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}
func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{1}
}

type GetContactByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactByIdRequest) Reset()         { *m = GetContactByIdRequest{} }
func (m *GetContactByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactByIdRequest) ProtoMessage()    {}
func (*GetContactByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{0}
}
func (m *GetContactByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactByIdRequest.Unmarshal(m, b)
}
func (m *GetContactByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetContactByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactByIdRequest.Merge(dst, src)
}
func (m *GetContactByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactByIdRequest.Size(m)
}
func (m *GetContactByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactByIdRequest proto.InternalMessageInfo

func (m *GetContactByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContactsByOwnerIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactsByOwnerIdRequest) Reset()         { *m = GetContactsByOwnerIdRequest{} }
func (m *GetContactsByOwnerIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactsByOwnerIdRequest) ProtoMessage()    {}
func (*GetContactsByOwnerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{1}
}
func (m *GetContactsByOwnerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsByOwnerIdRequest.Unmarshal(m, b)
}
func (m *GetContactsByOwnerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsByOwnerIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetContactsByOwnerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsByOwnerIdRequest.Merge(dst, src)
}
func (m *GetContactsByOwnerIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactsByOwnerIdRequest.Size(m)
}
func (m *GetContactsByOwnerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsByOwnerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsByOwnerIdRequest proto.InternalMessageInfo

func (m *GetContactsByOwnerIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetContactsByOwnerIdResponse struct {
	Contacts             []*ContactResponse `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetContactsByOwnerIdResponse) Reset()         { *m = GetContactsByOwnerIdResponse{} }
func (m *GetContactsByOwnerIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetContactsByOwnerIdResponse) ProtoMessage()    {}
func (*GetContactsByOwnerIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{2}
}
func (m *GetContactsByOwnerIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsByOwnerIdResponse.Unmarshal(m, b)
}
func (m *GetContactsByOwnerIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsByOwnerIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetContactsByOwnerIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsByOwnerIdResponse.Merge(dst, src)
}
func (m *GetContactsByOwnerIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetContactsByOwnerIdResponse.Size(m)
}
func (m *GetContactsByOwnerIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsByOwnerIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsByOwnerIdResponse proto.InternalMessageInfo

func (m *GetContactsByOwnerIdResponse) GetContacts() []*ContactResponse {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type ContactResponse struct {
	Audit                *Audit      `protobuf:"bytes,1,opt,name=audit,proto3" json:"audit,omitempty"`
	OwnerId              string      `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	UserId               string      `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string      `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	UserAlias            string      `protobuf:"bytes,5,opt,name=userAlias,proto3" json:"userAlias,omitempty"`
	AvatarId             string      `protobuf:"bytes,6,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	ContactType          ContactType `protobuf:"varint,7,opt,name=contactType,proto3,enum=proto.ContactType" json:"contactType,omitempty"`
	PhoneNumber          string      `protobuf:"bytes,8,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContactResponse) Reset()         { *m = ContactResponse{} }
func (m *ContactResponse) String() string { return proto.CompactTextString(m) }
func (*ContactResponse) ProtoMessage()    {}
func (*ContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{3}
}
func (m *ContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactResponse.Unmarshal(m, b)
}
func (m *ContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactResponse.Marshal(b, m, deterministic)
}
func (dst *ContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactResponse.Merge(dst, src)
}
func (m *ContactResponse) XXX_Size() int {
	return xxx_messageInfo_ContactResponse.Size(m)
}
func (m *ContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactResponse proto.InternalMessageInfo

func (m *ContactResponse) GetAudit() *Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func (m *ContactResponse) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *ContactResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ContactResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ContactResponse) GetUserAlias() string {
	if m != nil {
		return m.UserAlias
	}
	return ""
}

func (m *ContactResponse) GetAvatarId() string {
	if m != nil {
		return m.AvatarId
	}
	return ""
}

func (m *ContactResponse) GetContactType() ContactType {
	if m != nil {
		return m.ContactType
	}
	return ContactType_UnknownContactType
}

func (m *ContactResponse) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CallHistoryResponse struct {
	Audit                *Audit   `protobuf:"bytes,1,opt,name=audit,proto3" json:"audit,omitempty"`
	FromUserId           string   `protobuf:"bytes,2,opt,name=fromUserId,proto3" json:"fromUserId,omitempty"`
	ToUserId             string   `protobuf:"bytes,3,opt,name=toUserId,proto3" json:"toUserId,omitempty"`
	CallType             CallType `protobuf:"varint,4,opt,name=callType,proto3,enum=proto.CallType" json:"callType,omitempty"`
	Duration             int64    `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	ReferenceId          string   `protobuf:"bytes,6,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallHistoryResponse) Reset()         { *m = CallHistoryResponse{} }
func (m *CallHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*CallHistoryResponse) ProtoMessage()    {}
func (*CallHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_contact_5eec0de248930fe7, []int{4}
}
func (m *CallHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallHistoryResponse.Unmarshal(m, b)
}
func (m *CallHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallHistoryResponse.Marshal(b, m, deterministic)
}
func (dst *CallHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallHistoryResponse.Merge(dst, src)
}
func (m *CallHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_CallHistoryResponse.Size(m)
}
func (m *CallHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallHistoryResponse proto.InternalMessageInfo

func (m *CallHistoryResponse) GetAudit() *Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func (m *CallHistoryResponse) GetFromUserId() string {
	if m != nil {
		return m.FromUserId
	}
	return ""
}

func (m *CallHistoryResponse) GetToUserId() string {
	if m != nil {
		return m.ToUserId
	}
	return ""
}

func (m *CallHistoryResponse) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_UnknownCallType
}

func (m *CallHistoryResponse) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CallHistoryResponse) GetReferenceId() string {
	if m != nil {
		return m.ReferenceId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetContactByIdRequest)(nil), "proto.GetContactByIdRequest")
	proto.RegisterType((*GetContactsByOwnerIdRequest)(nil), "proto.GetContactsByOwnerIdRequest")
	proto.RegisterType((*GetContactsByOwnerIdResponse)(nil), "proto.GetContactsByOwnerIdResponse")
	proto.RegisterType((*ContactResponse)(nil), "proto.ContactResponse")
	proto.RegisterType((*CallHistoryResponse)(nil), "proto.CallHistoryResponse")
	proto.RegisterEnum("proto.ContactType", ContactType_name, ContactType_value)
	proto.RegisterEnum("proto.CallType", CallType_name, CallType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactServerClient is the client API for ContactServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactServerClient interface {
	GetContactById(ctx context.Context, in *GetContactByIdRequest, opts ...grpc.CallOption) (*ContactResponse, error)
	GetContactsByOwnerId(ctx context.Context, in *GetContactsByOwnerIdRequest, opts ...grpc.CallOption) (*GetContactsByOwnerIdResponse, error)
}

type contactServerClient struct {
	cc *grpc.ClientConn
}

func NewContactServerClient(cc *grpc.ClientConn) ContactServerClient {
	return &contactServerClient{cc}
}

func (c *contactServerClient) GetContactById(ctx context.Context, in *GetContactByIdRequest, opts ...grpc.CallOption) (*ContactResponse, error) {
	out := new(ContactResponse)
	err := c.cc.Invoke(ctx, "/proto.ContactServer/GetContactById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServerClient) GetContactsByOwnerId(ctx context.Context, in *GetContactsByOwnerIdRequest, opts ...grpc.CallOption) (*GetContactsByOwnerIdResponse, error) {
	out := new(GetContactsByOwnerIdResponse)
	err := c.cc.Invoke(ctx, "/proto.ContactServer/GetContactsByOwnerId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServerServer is the server API for ContactServer service.
type ContactServerServer interface {
	GetContactById(context.Context, *GetContactByIdRequest) (*ContactResponse, error)
	GetContactsByOwnerId(context.Context, *GetContactsByOwnerIdRequest) (*GetContactsByOwnerIdResponse, error)
}

func RegisterContactServerServer(s *grpc.Server, srv ContactServerServer) {
	s.RegisterService(&_ContactServer_serviceDesc, srv)
}

func _ContactServer_GetContactById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServerServer).GetContactById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContactServer/GetContactById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServerServer).GetContactById(ctx, req.(*GetContactByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactServer_GetContactsByOwnerId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsByOwnerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServerServer).GetContactsByOwnerId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ContactServer/GetContactsByOwnerId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServerServer).GetContactsByOwnerId(ctx, req.(*GetContactsByOwnerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ContactServer",
	HandlerType: (*ContactServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContactById",
			Handler:    _ContactServer_GetContactById_Handler,
		},
		{
			MethodName: "GetContactsByOwnerId",
			Handler:    _ContactServer_GetContactsByOwnerId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact.proto",
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_contact_5eec0de248930fe7) }

var fileDescriptor_contact_5eec0de248930fe7 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x6e, 0xd3, 0x4a,
	0x10, 0xc6, 0x6b, 0xa7, 0x49, 0xd3, 0x49, 0x9b, 0xf4, 0x4c, 0x9b, 0xc8, 0x27, 0x44, 0x28, 0x32,
	0x17, 0x44, 0x45, 0xea, 0x85, 0x81, 0x07, 0x48, 0x8b, 0xa0, 0xdc, 0x14, 0xc9, 0x6d, 0xb8, 0xdf,
	0xd8, 0x53, 0xb1, 0xc2, 0xde, 0x0d, 0xeb, 0x75, 0xab, 0x3c, 0x08, 0x6f, 0xc3, 0xc3, 0xf0, 0x28,
	0x68, 0xfd, 0x2f, 0x1b, 0x1a, 0x90, 0xb8, 0xb2, 0xe7, 0x37, 0xdf, 0xce, 0xcc, 0x37, 0xd2, 0xc0,
	0x71, 0x24, 0x85, 0x66, 0x91, 0xbe, 0x58, 0x29, 0xa9, 0x25, 0xb6, 0x8b, 0xcf, 0xf8, 0x28, 0x92,
	0x69, 0x2a, 0x45, 0x09, 0xfd, 0x97, 0x30, 0xfc, 0x40, 0xfa, 0xaa, 0x14, 0x5e, 0xae, 0x3f, 0xc6,
	0x21, 0x7d, 0xcb, 0x29, 0xd3, 0xd8, 0x07, 0x97, 0xc7, 0x9e, 0x33, 0x75, 0x66, 0x87, 0xa1, 0xcb,
	0x63, 0xff, 0x2d, 0x3c, 0xdb, 0x08, 0xb3, 0xcb, 0xf5, 0xa7, 0x47, 0x41, 0x6a, 0x23, 0x1f, 0x41,
	0x27, 0xcf, 0x0c, 0xa8, 0x9e, 0x54, 0x91, 0x1f, 0xc2, 0x64, 0xf7, 0xb3, 0x6c, 0x25, 0x45, 0x46,
	0x18, 0x40, 0xb7, 0x9a, 0x32, 0xf3, 0x9c, 0x69, 0x6b, 0xd6, 0x0b, 0x46, 0xe5, 0x64, 0x17, 0xd5,
	0x9b, 0x5a, 0x19, 0x36, 0x3a, 0xff, 0xbb, 0x0b, 0x83, 0xdf, 0xb2, 0xe8, 0x43, 0x9b, 0xe5, 0x31,
	0xd7, 0x45, 0xfb, 0x5e, 0x70, 0x54, 0x15, 0x99, 0x1b, 0x16, 0x96, 0x29, 0xf4, 0xe0, 0x40, 0x96,
	0xed, 0x3d, 0xb7, 0x18, 0xb2, 0x0e, 0xad, 0xe9, 0x5b, 0xf6, 0xf4, 0x38, 0x86, 0xae, 0xf9, 0xbb,
	0x61, 0x29, 0x79, 0xfb, 0x45, 0xa6, 0x89, 0x71, 0x02, 0x87, 0xe6, 0x7f, 0x9e, 0x70, 0x96, 0x79,
	0xed, 0x22, 0xb9, 0x01, 0xe6, 0x25, 0x7b, 0x60, 0x9a, 0x99, 0x9a, 0x9d, 0xf2, 0x65, 0x1d, 0xe3,
	0x1b, 0xe8, 0x55, 0x5e, 0xee, 0xd6, 0x2b, 0xf2, 0x0e, 0xa6, 0xce, 0xac, 0x1f, 0xe0, 0xb6, 0x6d,
	0x93, 0x09, 0x6d, 0x19, 0x4e, 0xa1, 0xb7, 0xfa, 0x22, 0x05, 0xdd, 0xe4, 0xe9, 0x92, 0x94, 0xd7,
	0x2d, 0x8a, 0xda, 0xc8, 0xff, 0xe9, 0xc0, 0xe9, 0x15, 0x4b, 0x92, 0x6b, 0x9e, 0x69, 0xa9, 0xd6,
	0xff, 0xb4, 0x9b, 0xe7, 0x00, 0xf7, 0x4a, 0xa6, 0x8b, 0xcc, 0x5a, 0x8f, 0x45, 0x8c, 0x1f, 0x2d,
	0x17, 0xf6, 0x8e, 0x9a, 0x18, 0x5f, 0x41, 0x37, 0x62, 0x49, 0x52, 0x98, 0xd9, 0x2f, 0xcc, 0x0c,
	0x6a, 0x33, 0x15, 0x0e, 0x1b, 0x81, 0x29, 0x14, 0xe7, 0x8a, 0x69, 0x2e, 0x45, 0xb1, 0xb5, 0x56,
	0xd8, 0xc4, 0xc6, 0xa2, 0xa2, 0x7b, 0x52, 0x24, 0x22, 0x6a, 0xf6, 0x66, 0xa3, 0xf3, 0x14, 0x7a,
	0xd6, 0x82, 0x70, 0x04, 0xb8, 0x10, 0x5f, 0x85, 0x7c, 0x14, 0x16, 0x3d, 0xd9, 0xc3, 0x33, 0x38,
	0x99, 0xc7, 0x29, 0xdf, 0xa2, 0x0e, 0xfe, 0x0f, 0xc3, 0xdb, 0x7c, 0x99, 0x45, 0x8a, 0x2f, 0x49,
	0xd9, 0x29, 0x17, 0x87, 0xf0, 0xdf, 0x7b, 0xc5, 0x49, 0xc4, 0x36, 0x6e, 0x9d, 0x47, 0xd0, 0xad,
	0x2d, 0xe0, 0x29, 0x0c, 0xea, 0x5e, 0x15, 0x2a, 0x1b, 0xdd, 0x51, 0xf2, 0x59, 0xf2, 0x88, 0x1a,
	0xea, 0x98, 0x6a, 0xef, 0x98, 0x66, 0xdb, 0xd8, 0x6d, 0x30, 0x8f, 0x49, 0x36, 0xb8, 0x15, 0xfc,
	0x70, 0xe0, 0xb8, 0x6a, 0x7b, 0x4b, 0xea, 0x81, 0x14, 0x5e, 0x43, 0x7f, 0xfb, 0x28, 0x71, 0x52,
	0x2d, 0x74, 0xe7, 0xad, 0x8e, 0xff, 0x70, 0x32, 0xfe, 0x1e, 0x32, 0x38, 0xdb, 0x75, 0x7e, 0xe8,
	0x3f, 0xa9, 0xf7, 0xe4, 0xa4, 0xc7, 0x2f, 0xfe, 0xaa, 0xa9, 0x5b, 0x2c, 0x3b, 0x85, 0xea, 0xf5,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x7f, 0x99, 0xa4, 0x6e, 0x04, 0x00, 0x00,
}
